name: "GitHub Action for Civo"
description: "Use civo to manage your Civo resources."
author: "Alejandro JNM <alejandro@civo.com>"
branding:
  icon: "play"
  color: "blue"
inputs:
  token:
    description: "Civo API Token"
    required: true
outputs:
  version:
    description: "The version of the civo cli"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.token }}
