name: "GitHub Action for Civo"
description: "Use civo to manage your Civo resources."
author: "Alejandro JNM <alejandro@civo.com>"
branding:
  icon: "play"
  color: "blue"
inputs:
  token:
    description: "Civo API Token"
    required: true
  version:
    description: 'Version of civo to install'
    default: 'latest'
outputs:
  version:
    description: "civo cli version"
runs:
  using: 'node16'
  main: 'dist/index.js'