on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to test the cli
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install civo
        uses: ./ # Uses an action in the root directory
        id: civocli
        with:
          token: 5446d7ad6b654c1ea9e305ad4933b66d # This is a fake token
      # Use the output from the `civo-cli` step
      - name: Check outputs
        run: |
          test "${{ steps.civocli.outputs.version }}" == "5446d7ad6b654c1ea9e305ad4933b66d"
      # - name: List the api keys
      #   run: civo apikey list
